### ISSUE TITLE
audio gives error OSError: exception: access violation reading 0xFFFFFFFFFFFFFFFF on windows

### ISSUE THREAD

**Issue by GXcells** [kivy/plyer#803] opened 2024-02-08 11:52 UTC
The example audio app from plyer (https://github.com/kivy/plyer/blob/master/examples/audio/main.py) does not work on windows nor on android (using pydroid to run kivy).

I get the error  "OSError: exception: access violation reading 0xFFFFFFFFFFFFFFFF" when clicking on the button Start Recording

This issue has been raised several times here but there is no fix.
It is a real pity because the plyer audio module is really clean/simple/straightforward compared to other python audio packages such as PyAudio and PYthonSounddevice.

PLEASE PLEASE PLEASE, could you try to fix it?

Here is the full error
Traceback (most recent call last):
   File "c:\Users\user\Documents\Python_projects\test\plyer_audio_kivy.py", line 118, in <module>
     AudioApp().run()
   File "c:\Users\user\.conda\envs\kivy\Lib\site-packages\kivy\app.py", line 956, in run
     runTouchApp()
   File "c:\Users\user\.conda\envs\kivy\Lib\site-packages\kivy\base.py", line 574, in runTouchApp
     EventLoop.mainloop()
   File "c:\Users\user\.conda\envs\kivy\Lib\site-packages\kivy\base.py", line 339, in mainloop
     self.idle()
   File "c:\Users\user\.conda\envs\kivy\Lib\site-packages\kivy\base.py", line 383, in idle
     self.dispatch_input()
   File "c:\Users\user\.conda\envs\kivy\Lib\site-packages\kivy\base.py", line 334, in dispatch_input
     post_dispatch_input(*pop(0))
   File "c:\Users\user\.conda\envs\kivy\Lib\site-packages\kivy\base.py", line 302, in post_dispatch_input
     wid.dispatch('on_touch_up', me)
   File "kivy\\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "c:\Users\user\.conda\envs\kivy\Lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
     self.dispatch('on_release')
   File "kivy\\_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
   File "kivy\\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
   File "kivy\\_event.pyx", line 1191, in kivy._event.EventObservers._dispatch
   File "c:\Users\user\.conda\envs\kivy\Lib\site-packages\kivy\lang\builder.py", line 60, in custom_callback
     exec(__kvlang__.co_value, idmap)
   File "<string>", line 22, in <module>
   File "c:\Users\user\Documents\Python_projects\test\plyer_audio_kivy.py", line 63, in start_recording
     self.audio.start()
   File "c:\Users\user\.conda\envs\kivy\Lib\site-packages\plyer\facades\audio.py", line 65, in start
     self._start()
   File "c:\Users\user\.conda\envs\kivy\Lib\site-packages\plyer\platforms\win\audio.py", line 329, in _start
     open_params = send_command(
                   ^^^^^^^^^^^^^
   File "c:\Users\user\.conda\envs\kivy\Lib\site-packages\plyer\platforms\win\audio.py", line 127, in send_command
     error_code = send_command_w(
                  ^^^^^^^^^^^^^^^
 OSError: exception: access violation reading 0xFFFFFFFFFFFFFFFF

**Comment by Julian-O** [comment] 2024-02-10 01:53
Duplicate of #656

**Closed by Julian-O** 2024-02-10 01:53 UTC
