### ISSUE TITLE
audio.start gives error  OSError: exception: access violation reading 0xFFFFFFFFFFFFFFFF

### ISSUE THREAD

**Issue by ghost** [kivy/plyer#749] opened 2023-03-10 12:56 UTC
this error arrives when i set file.path and run audio.start()
 OSError: exception: access violation reading 0xFFFFFFFFFFFFFFFF
 i have tried python 3.8,3.9 and 3.10 they all have the same error on terminal and on pycharm,
 
 do i need to install some additional library or change some settings ?

**Comment by misl6** [comment] 2023-03-11 09:04
Hi @chetanrana-lab !

Can you please provide some more context about this issue? (Platform, minimum reproducible example, and logs)

**Comment by chetanrana-lab** [comment] 2023-03-11 11:28
this was a example i was working on i am using conda environment in windows with python 3.10, error i have attached at the end, thanks for the reply man, i just started working on it again .
`from kivy.app import App
from kivy.lang import Builder
from kivy.properties import NumericProperty
from kivy.properties import ObjectProperty
from kivy.uix.boxlayout import BoxLayout


Builder.load_string('''
#:import audio_player plyer.audio
<AudioInterface>:
    audio: audio_player
    orientation: 'vertical'
    padding: '50dp'
    spacing: '20dp'
    Label:
        id: state_label
        size_hint_y: None
        height: sp(40)
        text: 'AudioPlayer State: ' + str(root.audio.state)
    Label:
        id: location_label
        size_hint_y: None
        height: sp(40)
        text: 'Recording Location: ' + str(root.audio.file_path)
    Button:
        id: record_button
        text: 'Start Recording'
        on_release: root.start_recording()
    Button:
        id: play_button
        text: 'Play'
        on_release: root.play_recording()
''')


class AudioInterface(BoxLayout):
    '''Root Widget.'''

    audio = ObjectProperty()
    time = NumericProperty(0)

    has_record = False

    def start_recording(self):
        state = self.audio.state
        if state == 'ready':
            self.audio.start()

        if state == 'recording':
            self.audio.stop()
            self.has_record = True

        self.update_labels()

    def play_recording(self):
        state = self.audio.state
        if state == 'playing':
            self.audio.stop()
        else:
            self.audio.play()

        self.update_labels()

    def update_labels(self):
        record_button = self.ids['record_button']
        play_button = self.ids['play_button']
        state_label = self.ids['state_label']

        state = self.audio.state
        state_label.text = 'AudioPlayer State: ' + state

        play_button.disabled = not self.has_record

        if state == 'ready':
            record_button.text = 'Start Recording'

        if state == 'recording':
            record_button.text = 'Press to Stop Recording'
            play_button.disabled = True

        if state == 'playing':
            play_button.text = 'Stop'
            record_button.disabled = True
        else:
            play_button.text = 'Press to play'
            record_button.disabled = False


class AudioApp(App):

    def build(self):
        return AudioInterface()

    def on_pause(self):
        return True


if __name__ == "__main__":
    AudioApp().run()`
    
    
    
     Traceback (most recent call last):
   File "E:\Mission_panchkula\Yolov8_custom\KWC\plyer1.py", line 99, in <module>
     AudioApp().run()
   File "C:\Users\user\anaconda3\envs\kivy_app\lib\site-packages\kivy\app.py", line 955, in run
     runTouchApp()
   File "C:\Users\user\anaconda3\envs\kivy_app\lib\site-packages\kivy\base.py", line 574, in runTouchApp
     EventLoop.mainloop()
   File "C:\Users\user\anaconda3\envs\kivy_app\lib\site-packages\kivy\base.py", line 339, in mainloop
     self.idle()
   File "C:\Users\user\anaconda3\envs\kivy_app\lib\site-packages\kivy\base.py", line 383, in idle
     self.dispatch_input()
   File "C:\Users\user\anaconda3\envs\kivy_app\lib\site-packages\kivy\base.py", line 334, in dispatch_input
     post_dispatch_input(*pop(0))
   File "C:\Users\user\anaconda3\envs\kivy_app\lib\site-packages\kivy\base.py", line 302, in post_dispatch_input
     wid.dispatch('on_touch_up', me)
   File "kivy\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\user\anaconda3\envs\kivy_app\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
     self.dispatch('on_release')
   File "kivy\_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
   File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1191, in kivy._event.EventObservers._dispatch
   File "C:\Users\user\anaconda3\envs\kivy_app\lib\site-packages\kivy\lang\builder.py", line 55, in custom_callback
     exec(__kvlang__.co_value, idmap)
   File "<string>", line 21, in <module>
   File "E:\Mission_panchkula\Yolov8_custom\KWC\plyer1.py", line 47, in start_recording
     self.audio.start()
   File "C:\Users\user\anaconda3\envs\kivy_app\lib\site-packages\plyer\facades\audio.py", line 65, in start
     self._start()
   File "C:\Users\user\anaconda3\envs\kivy_app\lib\site-packages\plyer\platforms\win\audio.py", line 329, in _start
     open_params = send_command(
   File "C:\Users\user\anaconda3\envs\kivy_app\lib\site-packages\plyer\platforms\win\audio.py", line 127, in send_command
     error_code = send_command_w(
 OSError: exception: access violation reading 0xFFFFFFFFFFFFFFFF

**Comment by chetanrana-lab** [comment] 2023-03-11 11:30
i have tried using example given in plyer.py examples it seems like there is some permission issue or i have some library compatibility issue.

**Comment by h6dworker** [comment] 2023-05-18 10:21
"""
jnius.jnius.JavaException: JVM exception occurred: /sdcard/testrecorder.3gp: open failed: EPERM (Operation not permitted) java.io.FileNotFoundException
"""

I tried granting app permissions on Android, but what is the compatibility based on recent versions?

**Comment by Julian-O** [comment] 2024-02-10 01:53
Duplicate of #656

**Closed by Julian-O** 2024-02-10 01:53 UTC
Labels: platform-win
