### ISSUE TITLE
plyer.notification invoke frequency

### ISSUE THREAD

**Issue by g8up** [kivy/plyer#513] opened 2019-09-10 16:47 UTC
```python
plyer.notification(title="Start", timeout=1)
# do_something(); # less than 1 sec
plyer.notification(title="Finished")
```
(Windows7, Python 3.6)
As I test, one`plyer.notification()` must delay 2 second after the last one, or it will not show out

How to reduce the delay time ?

**Comment by Julian-O** [comment] 2023-10-26 11:13
Closing as a resolved support question, not a bug report.

**Closed by Julian-O** 2023-10-26 11:13 UTC
Labels: support
