### ISSUE TITLE
Plyer notification doesn't work on Android

### ISSUE THREAD

**Issue by PythonLaboratory** [kivy/plyer#747] opened 2023-02-25 08:20 UTC
This code throws an error `NotImplementedError` on Android 13

```python
from plyer import notification

notification.notify(title='hello', message='Notification')
```

**Comment by misl6** [comment] 2023-02-26 16:37
Hi @PythonLaboratory !

The use case is the same reported in #748 ?

**Comment by PythonLaboratory** [comment] 2023-02-26 17:53
@misl6 Yes

**Comment by misl6** [comment] 2023-02-28 20:09
Duplicate of #748

**Closed by misl6** 2023-02-28 20:09 UTC
Labels: awaiting-reply
