### ISSUE TITLE
When I run the application on my smartphone, the application crashes and gives an error in logcat [WARNING] [Base ] Unknown <android> provider

### ISSUE THREAD

**Issue by Vladislav001414** [kivy/plyer#736] opened 2023-01-14 01:34 UTC
When launched on my smartphone, the application crashes as soon as I enter it, in logcat it gives the following error: [WARNING] [Base] Unknown <android> provider
On the bluestacks emulator, everything works fine on other phones, too, on mine. 
My phone is Oppo A53 
Android version 12
![image](https://user-images.githubusercontent.com/120846729/212444320-b37ecffd-fd94-4ff0-8d30-708708dc62b5.png)
![image](https://user-images.githubusercontent.com/120846729/212444448-506dfd58-8059-4ca8-bffe-966e69ee50e8.png)
![image](https://user-images.githubusercontent.com/120846729/212444497-595ae7e0-58eb-446a-b0d4-a1876868c4e1.png)
![image](https://user-images.githubusercontent.com/120846729/212444538-526fd93a-2382-415e-88a4-b50e5a32ef3a.png)
![image](https://user-images.githubusercontent.com/120846729/212444552-7868f28b-f90f-4d48-844f-6f4931562ac3.png)
![image](https://user-images.githubusercontent.com/120846729/212444569-a5ef55c2-c77b-4a45-b058-11aef12e1fda.png)

**Comment by misl6** [comment] 2023-01-14 09:17
Duplicate of https://github.com/kivy/buildozer/issues/1545

**Closed by misl6** 2023-01-14 09:17 UTC
