### ISSUE TITLE
uuid not unique on cloned windows system

### ISSUE THREAD

**Issue by merlink01** [kivy/plyer#540] opened 2020-02-21 13:14 UTC
Typically an uuid should be genrated by using hardware ids. 
Currently 2 cloned windows 7 machines have the same uuid (because it comes from the registry).
I could workout a solution for this.

**Comment by merlink01** [comment] 2020-02-21 16:16
Here is the solution I would prefer on Windows:
`import wmi
import hashlib
def get_uuid():
    c = wmi.WMI()
    
    #Simply get the Serial fom Mainboard
    mainboard_serial = None
    for i in c.Win32_ComputerSystemProduct():
        mainboard_serial = i.UUID.strip()
    #This works most of the time, except some OEM vedors  
        
    
    #Get the Serial from System Drive    
    systemdisk_serial_hex = None
    
    #Get the Operating System drive letter
    drive_letter = c.Win32_OperatingSystem()[0].SystemDrive
    
    #Find the Physical Disk of the System partition 
    for physical_disk in c.Win32_DiskDrive ():
        for partition in physical_disk.associators ("Win32_DiskDriveToDiskPartition"):
            for logical_disk in partition.associators ("Win32_LogicalDiskToPartition"):
                if logical_disk.Caption == drive_letter:
                    systemdisk_serial_hex = physical_disk.SerialNumber.strip()
    
    #This Serial is encoded in hex, if you want to see it correcly,
    #ask me I can give you the code.
    systemdisk_serial_hex = systemdisk_serial_hex.strip()
    
    
    print(mainboard_serial,systemdisk_serial_hex)
    
    #Hash both with sha256 for one unique hash
    h = hashlib.sha256()
    h.update(mainboard_serial.encode('utf-8'))
    h.update(systemdisk_serial_hex.encode('utf-8'))
    return str(h.hexdigest())

print(get_uuid())`

**Comment by merlink01** [comment] 2020-02-21 16:37
Here is why I prefer this solution:

There are a lot of solutions out there:

### Processor Serial: 
Intel removed it from newer processors because of privacy concerns

### MAC Address: 
there could be systems without network cards out there, they could be exchanged or the mac could be changed programatically
(also in the past I had problems with network drivers that were not available direcly after boot:
It took up to 30 seconds to become available)

### OperatingSystem.SerialNumber: 
This Serial changed in the past, after a big Windows Update

### MachineGuid (from registry):
This is currently implemented, every cloned windows machine has the same UUID here

So I think it's a good decision to use the Mainboard Serial and the System drive Serial.

**Comment by Julian-O** [comment] 2023-10-26 11:36
Closing as not a bug report or new feature request

**Closed by Julian-O** 2023-10-26 11:36 UTC
