### ISSUE TITLE
Error: 'Notify' attribute not found in module 'Plyer'

### ISSUE THREAD

**Issue by momoblydblk** [kivy/plyer#334] opened 2017-05-06 23:53 UTC
Exception in shell when calling `notification.notify`:
`AttributeError: module 'plyer.notification' has no attribute 'notify'`

**Comment by malverick** [comment] 2017-07-14 16:21
As you can see [here](https://github.com/kivy/plyer/blob/master/plyer/facades/notification.py#L26) that notify is a method which accepts some parameters to give result. 
You command would be correct if notify was a property of class Notification.
If you understand what I am saying then please close this issue or feel free to ask anything.

**Comment by KeyWeeUsr** [comment] 2018-10-15 21:43
Please check again with the latest release of plyer (`1.3.1`) and open a new issue if the problem is still present.

**Closed by KeyWeeUsr** 2018-10-15 21:43 UTC
Labels: question
