### ISSUE TITLE
STT starts-stops

### ISSUE THREAD

**Issue by ignamendi21** [kivy/plyer#730] opened 2022-12-11 21:33 UTC
Hei, I have implemented the example of STT and added the permisions for audio recording. It worked in my previous phone, but I have bougth a new phone and it doesn work. The same apk. When I click "start listening" it "stops" consecuently....

**Comment by misl6** [comment] 2023-01-21 10:35
Duplicate of #573

**Closed by misl6** 2023-01-21 10:35 UTC

**Comment by 20fake** [comment] 2023-06-05 06:35
Hey, I'm working on Kivy app and having the same problem when the apk tries to record my voice, but the microphone is not responding. I'm using android 11 for my kivy apk. 

I think I have found the solution (in my case it worked) if you are using android 11 (API 30).
I just targeted android.api in buildozer to API 29, and here are my requirements:

requirements = python3,kivy==2.1.0,kivymd==1.0.2,pillow,sqlite3,plyer,pyjnius,android

# (int) Target Android API, should be as high as possible.
android.api = 29

Hope my answer help you out
