### ISSUE TITLE
Python for Android Setting up the readme

### ISSUE THREAD

**Issue by jjccvt** [kivy/plyer#506] opened 2019-07-09 12:05 UTC
I've looked at the readme as below that was issued but I'm not sure how to implement these into my build? Please assist I am new to this....

Basic camera example.
Default picture is saved as /sdcard/org.test.cameraexample/enter_file_name_here.jpg

Python-for-android compilation:

	./distribute.sh -m 'kivy plyer'
	cd dist/default
	./build.py --org.test.cameraexample --name "Kivy Camera Example" \
		--dir /path/to/plyer/examples/camera/basic --version 1.0 \
		debug installd 

Buildozer:

	cd /path/to/plyer/examples/camera/basic
	# edit the buildozer.spec if required, then
	buildozer android debug deploy run

**Comment by Python3-8** [comment] 2020-08-14 21:13
Can you please describe more about your issue? Are you trying to build your app or are you having issues with the camera feature?

**Comment by Julian-O** [comment] 2023-10-26 10:43
Closing as a Support request, not a bug report.

**Closed by Julian-O** 2023-10-26 10:43 UTC
Labels: support
