### ISSUE TITLE
take_picture fails to execute

### ISSUE THREAD

**Issue by shixudongleo** [kivy/plyer#295] opened 2017-03-06 11:16 UTC
I am using the kivy VM (virtual machine) for compiling. it reports an error, when camera.take_picture is called. how to fix this error? 

```shell
6781 I/python  ( 5000):  Exception in thread Thread-1:                        
16782 I/python  ( 5000):  Traceback (most recent call last):                   
16783 I/python  ( 5000):    File "/home/kivy/Projects/camera/.buildozer/android/platform/python-for-android/build/python-instal      l/lib/python2.7/threading.py", line 552, in __bootstrap_inner
16784 I/python  ( 5000):    File "/home/kivy/Projects/camera/.buildozer/android/platform/python-for-android/build/python-instal      l/lib/python2.7/threading.py", line 505, in run
16785 I/python  ( 5000):    File "/home/kivy/Projects/camera/.buildozer/android/app/main.py", line 34, in display_current
16786 I/python  ( 5000):    File "/home/kivy/Projects/camera/.buildozer/android/platform/python-for-android/build/python-instal      l/lib/python2.7/site-packages/plyer/facades/camera.py", line 60, in take_picture
16787 I/python  ( 5000):    File "/home/kivy/Projects/camera/.buildozer/android/platform/python-for-android/build/python-instal      l/lib/python2.7/site-packages/plyer/platforms/android/camera.py", line 21, in _take_picture
16788 I/python  ( 5000):    File "/home/kivy/Projects/camera/.buildozer/android/platform/python-for-android/build/python-instal      l/lib/python2.7/site-packages/android/activity.py", line 44, in bind
16789 I/python  ( 5000):    File "/home/kivy/Projects/camera/.buildozer/android/platform/python-for-android/build/python-instal      l/lib/python2.7/site-packages/android/activity.py", line 27, in __init__
16790 I/python  ( 5000):    File "jnius/jnius_proxy.pxi", line 31, in jnius.jnius.PythonJavaClass.__init__ (jnius/jnius.c:24669      )
16791 I/python  ( 5000):    File "jnius/jnius_proxy.pxi", line 160, in jnius.jnius.create_proxy_instance (jnius/jnius.c:26877)
16792 I/python  ( 5000):    File "/home/kivy/Projects/camera/.buildozer/android/platform/python-for-android/build/python-instal      l/lib/python2.7/site-packages/jnius/reflect.py", line 150, in autoclass
16793 I/python  ( 5000):    File "jnius/jnius_export_func.pxi", line 23, in jnius.jnius.find_javaclass (jnius/jnius.c:13171)
16794 I/python  ( 5000):  JavaException: Class not found 'org/jnius/NativeInvocationHandler'
```

**Comment by malverick** [comment] 2017-03-11 08:15
Hi @shixudongleo , you can take help from [here](https://github.com/kivy/pyjnius/issues/137).

**Comment by KeyWeeUsr** [comment] 2018-10-15 21:41
Duplicate of #137.

**Closed by KeyWeeUsr** 2018-10-15 21:41 UTC
Labels: duplicate, platform-android
