### ISSUE TITLE
OS Back-end Error Using WSL 2

### ISSUE THREAD

**Issue by npel-21** [kivy/plyer#574] opened 2020-07-28 17:38 UTC
I'm trying to run an app which uses a plyer.filechooser.open_file call. However, when running in WSL 2 on Windows 10, I get an undetected OS error. The program uses a server in WSL 2's Ubuntu 16.04, but I'm making the open file call in a browser on the Windows 10 side. Is there a way to support this? 

```
Traceback (most recent call last):
  File ".../app.py", line 591, in import_log
    locations = plyer.filechooser.open_file(path=str(current_path), multiple=True)
  File ".../python3.8/site-packages/plyer/facades/filechooser.py", line 50, in open_file
    return self._file_selection_dialog(mode="open", *args, **kwargs)
  File ".../python3.8/site-packages/plyer/platforms/linux/filechooser.py", line 254, in _file_selection_dialog
    raise OSError("No back-end available. Please install one.")
OSError: No back-end available. Please install one.
```

**Comment by mateusamorim96** [comment] 2023-03-19 15:48
For those who might get stuck in that part too, here is what I did to partially solve this after look at the code https://github.com/kivy/plyer/blob/6fb47d9d71e02d70b9c0bae8a391daa1aaa76710/plyer/platforms/linux/filechooser.py#L235.

`sudo apt update && sudo upgrade`
`sudo apt install kde-plasma-desktop`
Open PowerShell as admin and
`wsl --shutdown`

Open Ubuntu again
`export XDG_CURRENT_DESKTOP="kde"`

By doing this I was able to open the file manager, but I'm still having errors like:
KCrash: Arguments: Qt: Session management error: networkIdsList argument is NULL

**Comment by mateusamorim96** [comment] 2023-03-19 16:13
Update:
I installed YAD and use it instead of KDE, looks like it is working fine now.

I've changed only XDG to avoid the system to call KDE
`export XDG_CURRENT_DESKTOP=""`

And installed YAD by
`sudo apt install yad`

**Comment by misl6** [comment] 2023-03-20 19:42
Duplicate of https://github.com/kivy/plyer/issues/739

**Closed by misl6** 2023-03-20 19:42 UTC
